language: ruby
bundler_args: --without development
rvm:
  - "1.9.3"
services: postgresql
before_install:
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database open_food_network_test;' -U postgres
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake spec
