language: ruby
sudo: false
cache: bundler
bundler_args: --without development
rvm:
  - "2.1.5"

# Set the timezone for phantomjs with TZ
# Set the timezone for karma with TIMEZONE
#
# The test cases are roughly split according to their test times.
# It would be better to use https://github.com/ArturT/knapsack.
env:
  global:
    - TZ="Australia/Melbourne"
    - TIMEZONE="Australia/Melbourne"

before_script:
  - cp config/database.travis.yml config/database.yml
  - cp config/application.yml.example config/application.yml
  - RAILS_ENV=test bundle exec rake db:create db:schema:load

  # Only install PhantomJS if it is not already present (ie. cached)
  - npm list -g phantomjs-prebuilt@~2.1.7 --depth=0 || npm install -g phantomjs-prebuilt@~2.1.7
  - export PATH=`npm bin -g`:$PATH

  - >
    if [ "$KARMA" = "true" ]; then
      npm install -g npm@'3.8.8'
      npm install
      npm install -g karma-cli@0.1.2
    fi

script:
  - 'if [ "$KARMA" = "true" ]; then bundle exec rake karma:run; else echo "Skipping karma run"; fi'
  #- "KNAPSACK_GENERATE_REPORT=true bundle exec rspec spec"
  - "bundle exec rspec spec/features/admin/reports_spec.rb"

after_success:
  - >
    if [ "$GITHUB_DEPLOY" = "true" -a "$TRAVIS_PULL_REQUEST" = "false" -a -n "$TRAVIS_BRANCH" -a "$TRAVIS_BRANCH" != "transifex" -a -n "$GITHUB_API_SECRET" ]; then
      description="`git show "$TRAVIS_BRANCH" -s --oneline --no-color`"
      data="{
        \"ref\":\"$TRAVIS_BRANCH\",
        \"description\":\"$description\",
        \"environment\":\"staging\",
        \"required_contexts\":[]}"
      curl -u "$GITHUB_API_SECRET" -d "$data" "https://api.github.com/repos/$TRAVIS_REPO_SLUG/deployments"
    else
      echo "Not deploying on this build."
    fi

notifications:
  email: false
