# Note: You must restart bin/webpack-dev-server for changes to take effect

default: &default
  source_path: app/webpacker
  source_entry_path: packs
  public_root_path: public
  public_output_path: packs
  cache_path: tmp/cache/webpacker
  webpack_compile_output: true

  # Additional paths webpack should look up modules
  # ['app/assets', 'engine/foo/app/assets']
  additional_paths: [
    'vendor',
    'app/webpacker/css',
    'app/webpacker/fonts',
    'app/webpacker/images',
    'engines/web/app/assets/stylesheets',
    'app/components'
  ]

  # Reload manifest.json on all requests so we reload latest compiled packs
  cache_manifest: false

  # Extract and emit a css file
  extract_css: true

test:
  <<: *default
  # Asset are precomiled on CI, so no need to compile here 
  compile: false 

  # Compile test packs to a separate directory
  public_output_path: packs-test
