development:
  adapter: postgresql
  encoding: unicode
  #template: template0
  #collate: en_US.UTF8
  #ctype: en_US.UTF8
  database: open_food_web_dev
  pool: 5
  host: localhost
  username: ofw
  password: f00d

test:
  adapter: postgresql
  encoding: unicode
  database: open_food_web_test
  pool: 5
  host: localhost
  username: ofw
  password: f00d

#not used with heroku
production:
  adapter: postgresql
  encoding: unicode
  database: open_food_web_prod
  pool: 5
  username: ofw
  password: f00d
