defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV.fetch('OFN_DB_HOST', 'localhost') %>
  username: <%= ENV.fetch('OFN_DB_USERNAME', 'ofn') %>
  password: <%= ENV.fetch('OFN_DB_PASSWORD', 'f00d') %>

development:
  <<: *defaults
  database: open_food_network_dev

test:
  <<: *defaults
  database: open_food_network_test

production:
  <<: *defaults
  database: open_food_network_prod

staging:
  <<: *defaults
  database: open_food_network_prod
